import { gameSettings } from "./gameSettings";

export const recruitmentConfig = {
  refreshIntervalDays: 30,
  pawnInventorySlots: 4,
  names: [
    "Ли Вэй",
    "Ван Чжи",
    "Чжан Мин",
    "Лю Ян",
    "Чэнь Цзе",
    "Ян Сю",
    "Чжао Лэй",
    "Хуан И",
    "Чжоу Фэн",
    "У Цянь",
    "Сюй Тао",
    "Сунь Ли",
    "Ма Чэнь",
    "Чжу Бо",
    "Ху Ган",
    "Го Вэнь",
    "Хэ Цзин",
    "Гао Шань",
    "Линь Фэн",
    "Ло Пин",
    "Чжэн Кай",
    "Лян Юй",
    "Се Тянь",
    "Сун Цзян",
    "Тан Вэй",
    "Сюй Хай",
    "Хань Бин",
    "Цао Юн",
    "Дэн Сяо",
    "Цзэн И",
    "Пэн Фэй",
    "Цай Цзюнь",
    "Тянь Юй",
    "Жэнь Цзе",
    "Цзян Тао",
    "Фань Вэй",
    "Ши Лэй",
    "Яо Мин",
    "Тань Цун",
    "Шэн Ли",
    "Цзоу Цян",
    "Сюн Фэй",
    "Цзинь Лун",
    "Вэй Чэнь",
    "Тао Юань",
    "Мэн Хао",
    "Цинь Ху",
    "Цю Чжэн",
    "Бай Юнь",
    "Ду Лэй",
  ],
};

export function getRandomName(): string {
  const randomIndex = Math.floor(Math.random() * recruitmentConfig.names.length);
  return recruitmentConfig.names[randomIndex];
}
